### ISSUE TITLE
Release plan of 3.5.1

### ISSUE THREAD

**Issue by zwxue** [codehaus-plexus/plexus-io#136]
Hello, we got a performance issue on our product and we can't downgrade related dependencies because of CVE, may I ask when will plexus-io 3.5.1 be released?

**Comment by slawekjaranowski** [comment]
issues and PR https://github.com/codehaus-plexus/plexus-io/milestone/7?closed=1

I will do it.

**Comment by gnodet** [comment]
@slawekjaranowski I wanted to do the release, but the deployment has been rejected, so I suppose I don't have the needed permissions on OSS repo.  Would you mind doing the deployment ?

**Comment by cstamas** [comment]
@slawekjaranowski then tried myself as well, same thing :smile:

**Comment by slawekjaranowski** [comment]
@gnodet , @cstamas 
ups ... I have the same 403. forbidden for release and also for snapshot repositories.

We need ask sonatype

**Comment by slawekjaranowski** [comment]
I was recreate my tokens and it is the same, with the same token I can deploy to other repos, like mojohause

**Comment by olamy** [comment]
same here.
did someone opened a ticket to sonatype?

**Comment by slawekjaranowski** [comment]
I will do it

**Comment by slawekjaranowski** [comment]
@gnodet - permissions was restored
I have deployed 3.5.1 - should be visible in some minutes
docs site also was refreshed

**Comment by slawekjaranowski** [comment]
it is visible: https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-io/3.5.1/

**Comment by gnodet** [comment]
Awesome, thx a ton @slawekjaranowski !
