### ISSUE TITLE
Extremely slow archiving when changing between plexus-io 2.6 and 2.6.1

### ISSUE THREAD

**Issue by Classe** [codehaus-plexus/plexus-io#16]
Please see https://github.com/codehaus-plexus/plexus-archiver/issues/105

**Comment by Classe** [comment]
I've found the issue, its somewhat the group and owner cache that isn't working as expected. 
Files.readAttributes( path, "unix:*", LinkOption.NOFOLLOW_LINKS );
This fetches group name and owner name directly. So that cache doesn't make sense.
I've made a patch which only fetches "unix:permissions,gid,uid,isSymbolicLink". 
And if gid/uid not in cache it fetches "group" and "owner".

**Comment by Classe** [comment]
Would it be possible to do a release of this soon? :+1:

**Comment by olamy** [comment]
@Classe sounds definitely a good idea! @plamentotev let me know if you do not have the bandwidth and I can help. Otherwise ship it!! :)

**Comment by plamentotev** [comment]
Yes, indeed it is a good idea. I can do a release later today.
